### ISSUE TITLE
为什么地图上会出现这个方框呢?

### ISSUE THREAD

**Issue by dfaofeng** [lanseria/xuyun-travel-map#1]
![image](https://user-images.githubusercontent.com/14891398/217524876-aa53bdd9-3662-446e-bb51-3f4bdf29b400.png)
还有增加数据的方法是自己写定位json的吗?gpx信息怎么获得?

**Comment by lanseria** [comment]
就表示当前路线范围吧，觉得没必要可去

2023年2月8日 20:06，蒋 ***@***.***> 写道：



[image]<https://user-images.githubusercontent.com/14891398/217524876-aa53bdd9-3662-446e-bb51-3f4bdf29b400.png>
还有增加数据的方法是自己写定位json的吗?gpx信息怎么获得?

**Comment by lanseria** [comment]
> ![image](https://user-images.githubusercontent.com/14891398/217524876-aa53bdd9-3662-446e-bb51-3f4bdf29b400.png) 还有增加数据的方法是自己写定位json的吗?gpx信息怎么获得?

我做了快速录数据的工具，gpx也是可以快速获取，会发视频讲一下
